export function generateContentForFile({
  cssVariables,
  geneateDisclaimer = false,
  mixinName,
}: {
  cssVariables: string;
  geneateDisclaimer?: boolean;
  mixinName?: string;
}) {
  let content = mixinName
    ? `@mixin ${mixinName} {\n${cssVariables}\n}`
    : `:root {\n${cssVariables}\n}`;
  if (geneateDisclaimer) {
    // Add disclaimer to every file if enabled
    content = `/* This file was generated by Supernova, don't change by hand */\n${content}`;
  }

  return content;
}
