export function generateContentForFile({
  cssVariables,
  geneateDisclaimer = false,
  mixinName,
  imports = [],
}: {
  cssVariables: string;
  geneateDisclaimer?: boolean;
  mixinName?: string;
  imports?: string[];
}) {
  let content = imports.length
    ? `/* Necessary imports for standalone imports of this file, do not remove */ \n ${imports.map(
        (importName) => `@import "${importName}"; \n`
      )}`
    : "";
  content = `${content} \n ${
    mixinName
      ? `@mixin ${mixinName} {\n${cssVariables}\n}`
      : `:root {\n${cssVariables}\n}`
  }`;

  if (geneateDisclaimer) {
    // Add disclaimer to every file if enabled
    content = `/* This file was generated by Supernova, don't change by hand */\n${content}`;
  }

  return content;
}
